# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: d6854dd680c58e180766c7208d6777667d4c424149fb2dc2532bfe789e9b96fa45873312d95c34dc291c9e9e1bb15706d1ea14743943b85311f30e3f085dc622

test:
  secret_key_base: 1485954724e46976edb980c87d69fba29ee3d2aa4cb69b54f32cb108c27b5e53065901b41a914227e6bb25b3a928b30fa6d68feebd8a5365035d51ad6267b76a

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
